name: AI Test Generation

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  generate-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - run: mvn clean compile

      - name: Scan @AutoTest APIs
        run: mvn exec:java -Dexec.mainClass="com.example.poc_test_generation.utils.AutoTestScannerRunner" > autogen-api-list.txt

      - name: Authenticate Co-Pilot
        run: gh auth login --with-token ${{ secrets.GH_COPILOT_TOKEN }}

      - name: Generate tests via Enterprise Co-Pilot
        run: |
          while read -r method; do
            gh co-pilot generate tests --class "$method" --output "src/test/java"
          done < autogen-api-list.txt

      - name: Commit generated tests
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add src/test/java
          git commit -m "Generated tests via Co-Pilot" || echo "No changes to commit"
          git push
